artists = [
'Logic',
'Rihanna',
'Frank Sinatra',
'The Beatles',
'Bob Dylan',
'Elvis Presley',
'Rolling Stones',
'Chuck Berry',
'Jimi Hendrix',
'James Brown',
'Little Richard',
'Aretha Franklin',
'Ray Charles',
'Bob Marley',
'The Beach Boys',
'Buddy Holly',
'Led Zeppelin',
'Stevie Wonder',
'Sam Cooke',
'Muddy Waters',
'Marvin Gaye',
'The Velvet Underground',
'Bo Diddley',
'Otis Redding',
'U2',
'Bruce Springsteen',
'Jerry Lee Lewis',
'Fats Domino',
'The Ramones',
'Nirvana',
'Prince',
'The Who',
'The Clash',
'Johnny Cash',
'Smokey Robinson & The Miracles',
'The Everly Brothers',
'Neil Young',
'Michael Jackson',
'Madonna',
'Roy Orbison',
'John Lennon',
'David Bowie',
'Simon and Garfunkel',
'The Doors',
'Van Morrison',
'Sly and the Family Stone',
'Public Enemy',
'The Byrds',
'Janis Joplin',
'Patti Smith',
'Run-DMC',
'Elton John',
'The Band',
'Howlin Wolf',
'Allman Brothers Band',
'Eric Clapton',
'Dr. Dre',
'Grateful Dead',
'Parliament Funkadelic',
'Aerosmith',
'Sex Pistols',
'Louis Jordan',
'Joni Mitchell',
'Tina Turner',
'Etta James',
'Phil Spector',
'The Kinks',
'Al Green',
'Cream',
'The Temptations',
'Jackie Wilson',
'Carl Perkins',
'The Police',
'Frank Zappa',
'AC/DC',
'Radiohead',
'Hank Williams',
'The Eagles',
'The Shirelles',
'Beastie Boys',
'The Stooges',
'The Four Tops',
'Elvis Costello',
'The Drifters',
'Eminem',
'N.W.A.',
'James Taylor',
'Black Sabbath',
'Tupac Shakur',
'Gram Parsons',
'Miles Davis',
'The Yardbirds',
'Carlos Santana',
'Ricky Nelson',
'Guns n Roses',
'Booker T. and the MG',
'Nine Inch Nails',
'Lynyrd Skynyrd',
'Martha and the Vandellas',
'Diana Ross and the Supremes',
'Roxy Music',
'Curtis Mayfield',
'Lee Scratch Perry'
'Linkin Park',
'Avenged Sevenfold',
'Green Day',
'Snow Patrol',
'Korn',
'Nickelback',
'Slipknot',
'Fall Out Boy',
'System of a Down',
'Blink-182',
'Creed',
'Radiohead',
'Killswitch Engage',
'Coldplay',
'Disturbed',
'The Click Five',
'Porcupine Tree',
'Foo Fighters',
'Underoath',
'Audioslave',
'Papa Roach',
'Sum 41',
'Bullet For My Valentine',
'Tool',
'The Strokes',
'Weezer',
'Limp Bizkit',
'My Chemical Romance',
'Trivium',
'Animal Collective',
'Lifehouse',
'Deftones',
'Godsmack',
'Bon Jovi',
'Alter Bridge',
'Nine Inch Nails',
'Good Charlotte',
'Modest Mouse',
'Franz Ferdinand',
'Meshuggah',
'Drowning Pool',
'Switchfoot',
'Death Cab For Cutie',
'Jimmy Eat World',
'The Offspring',
'Interpol',
'Kings of Leon',
'The Bravery',
'Puddle of Mudd',
'Stained',
'The Black Keys',
'Muse',
'Breaking Benjamin',
'30 Seconds To Mars',
'U2',
'Hoobastank',
'New Found Glory',
'Evanescence',
'Yeah Yeah Yeahs',
'Seether',
'The Killers',
'Wiclo',
'Paramore',
'Our Lady Peace',
'Maroon 5',
'Queens of the Stone Age',
'LCD Soundsystem',
'Pearl Jam',
'Simple Plan',
'The Hives',
'Metallica',
'Arctic Monkeys',
'Red Hot Chili Peppers',
'The All-American Rejects',
'Shinedown',
'Rilo Kiley',
'Coheed and Cambria',
'The Vines',
'Skillet',
'Aerosmith',
'The Mars Volta',
'Shadows Fall',
'Daughtry',
'The Fray',
'The Black Dahlia Murder',
'Kaiser Chiefs',
'Incubus',
'AC/DC',
'Arcade Fire',
'Lamb of God',
'Opeth',
'Spoon',
'Nightwish',
'Dream Theater',
'Mastadon',
'Barenaked Ladies',
'Symphony X',
'Three Days Grace',
'The Von Bondies',
'Hatebreed',
'Olivia Rodrigo',
'Taylor Swift',
'Eminem',
'Juice WRLD',
'Drake',
'Ed Sheeran',
'J. Cole',
'Ariana Grande',
'Kanye West',
'Justin Bieber',
'Lana Del Rey',
'Billie Eilish',
'Julia Michaels',
'The Weeknd',
'Kendrick Lamar',
'BTS',
'Cardi B',
'Travis Scott',
'Lady Gaga',
'Mariah Carey',
'John Legend',
'Justin Timerlake',
'Usher',
'Beyoncé',
'Pharrell Williams',
'Alicia Keys',
'Kelly Clarkson',
'Katy Perry',
'Adele',
'Akon',
'Bruno Mars',
'Selena Gomez',
'Khalid',
'Imagine Dragons',
'One Direction',
'James TW',
'Lewis Capaldi',
'Lauv',
'Maisie Peters',
'Alec Benjamin',
'Lorde',
'James Arthur',
'Dean Lewis',
'Jacob Lee',
'Calum Scott',
'Troye Sivan',
'Passenger',
'John Mayer',
'James Bay',
'Sam Smith',
'Shawn Mendes'
]

artists2 = ['youngboy never broke again','lil nas x','doja cat','lil baby','morgan wallen','rod wave','bad bunny','future','post malone','pop smoke','polo g','luke combs','lil uzi vert','lil durk','trippie redd','$uicideboy$','lil wayne','moneybagg yo','xxxtentacion','mac miller','the kid laroi','dababy','gunna','kevin gates','jack harlow','chris stapleton','tyler, the creator','jason aldean','chris brown','playboi carti','kodak black','megan thee stallion','dua lipa','a boogie wit da hoodie','g-eazy','young thug','meek mill','machine gun kelly','j. balvin','nf','baby keem','migos','luke bryan','nicki minaj','glass animals','lil tecca','halsey','thomas rhett','harry styles','fleetwood mac','kane brown','kid cudi','florida georgia line','queen','roddy ricch','dj khaled','21 savage','jhené aiko','lil peep','frank ocean','sleepy hallow','ynw melly','lil tjay','giveon','twenty one pilots','h.e.r','kacey musgraves','king von','blackbear','dan + shay','rauw alejandro','eslabon armado','eric church','george strait','2pac','tyler childers','pooh shiesty','kenny chesney','eagles','miley cyrus','blake shelton','russ','jay-z','sza','panic! at the disco','grupo firme','gucci mane','walker hayes','sam hunt','lee brice','42 dugg','the neighbourhood','tory lanez','the rolling stones','brent faiyaz','zac brown band','metro boomin','p!nk','nle choppa','summer walker','farruko','ozuna','kehlani','the lumineers','g herbo','a$ap rocky','karol g','wiz khalifa','miranda lambert','carrie underwood','maluma','joyner lucas','tom petty','onerepublic','notorious b.i.g.','big sean','est gee','joji','marshmello','bryson tiller','pitbull','jelly roll','tim mcgraw','old dominion','pink floyd','cody johnson','wizkid','childish gambino','five finger death punch','ajr','alan jackson','jonas brothers','upchurch','young dolph','original broadway cast of hamilton','calvin harris','jordan davis','billy joel','don toliver','50 cent','jon pardi','nelly','mo3',"guns n' roses",'anuel aa','big30','ski mask the slump god','marca mp','bo burnham','willow','creedence clearwater revival','gorillaz','lizzo','melanie martinez','maren morris','brooks & dunn','daddy yankee','aventura','tame impala','6lack','key glock','jason derulo','the chainsmokers','britney spears','nocap','camila cabello','demi lovato','trey songz','partynextdoor','iann dior','myke towers','dierks bentley','journey','cage the elephant','chris young','miguel','brantley gilbert','t.i.','elevation worship','justin timberlake','outkast','jack johnson','tee grizzley','hozier','keith urban','romeo santos','junior h','5 seconds of summer','tyga','jhay cortez','yung bleu','alessia cara','mitski','young jeezy','dustin lynch','kali uchis','nipsey hussle','sheff g','nav','cocomelon','måneskin','westside gunn','clairo','brett young','sublime','earth wind & fire','money man','jeremih','24kgoldn','christian nodal','greta van fleet','chief keef','2 chainz','ty dolla $ign','nas','toby keith','van halen','conan gray','tate mcrae','david guetta','el fantasma','shakira','t-pain','lil yachty','natanael cano','the black eyed peas','flo rida','calibre 50','parker mccollum','cole swindell','lauren daigle','saweetie','ne-yo','cody jinks','kelsea ballerini','banda sinaloense ms de sergio lizárraga','oliver tree','toosii','koe wetzel','bob marley, the wailers','gabby barrett','lil skies','michael bublé','steve lacy','garth brooks','rascal flatts','young nudy','bazzi','toby fox','riley green','tai verdes','jake owen','$not','mac demarco','wale','daryl hall, john oates','bring me the horizon','hardy','bebe rexha','rick ross','bee gees','zach bryan','schoolboy q','yo gotti','snoop dogg','bia','avicii','girl in red','cavetown','ella mai','ke$ha','luis r. conriquez','isaiah rashad','sech','los dos carnales','surfaces','rex orange county','yg','bob seger','sia','daniel caesar','pinkpantheress','whitney houston','lady a','mary j. blige','masked wolf','carin leon','lord huron','abba','los tucanes de tijuana','little big town','kid rock','mozzy','enya','darius rucker','brad paisley','alice in chains','justin moore','aaliyah','hillsong worship','mitchell tenpenny','carly pearce','enrique iglesias','shoreline mafia','billy currington','hank williams jr.','saint jhn','train','jazmine sullivan','mötley crüe','maverick city music','don omar','def leppard','chance the rapper','vance joy',"destiny's child",'chase atlantic','all time low','phil collins','diplo','ice cube','phoebe bridgers','tink','meghan trainor','yfn lucci','lil mosey','k camp','normani','3 doors down','colter wall','dj snake','los bukis','tech n9ne','lany','dmx','ava max','rae sremmurd','daft punk','los tigres del norte','city girls','chlöe','chase rice','nicky jam','jaydayoungan','selena','charlie puth','whiskey myers','a$ap ferg','foster the people','tones and i','hillsong united','silk sonic','ckay','sleepy john','mother mother','r. kelly','scotty mccreery','lainey wilson','smashing pumpkins','queen naija','vicente fernández','fetty wap','ellie goulding','kygo','lil darkie','comethazine','mumford & sons','vedo','ozzy osbourne','blackpink','ciara','yeat','a day to remember','fredo bang','avril lavigne','tom macdonald','casting crowns','niko moon','falling in reverse','los temerarios','ashnikko',"pi'erre bourne",'leon bridges','larry june','boney m.','steely dan','ryan hurd','sturgill simpson','bryce vine','willie nelson','jacquees','french montana','stray kids','blxst','jennifer lopez','needtobreathe','the chicks','alina baraz','quinn xcii']

#"alex (칸첸알렉스) (kor)","​​alt-j","amy winehouse","andrew lloyd webber","скриптонит & райда (skriptonite & raida)","嵐 (arashi)","atl","ayesha erotica","a1 x j1","a2h","a2m","a36","a4 (rus)","a92","ağaçkakan","aarne & lil krystalll","aaron cole","aaron keyes","aaron lewis","aaron may","aaron smith","aaron sorkin","aaron west & the roaring twenties","aaryan shah","ab6ix (에이비식스)","abbas bağırov","abbey glover","abby cates","abdullah siddiqui & talha anjum","abe parker","abhir hathi","abhi the nomad","abigail barlow","abo el anwar","aborted","above & beyond","aboveground germany","above the hood (grc)","above the law","abra","abra & boys noize","abra cadabra","abraham lincoln","abreu","abs-cbn music all-star","​absent","absofacto","żabson","ab-soul","abstract","abyusif","the acacia strain","the academic","aca lukas","acappella","accept","a.c.e","ace hood","ace of base","a.chal","achille lauro","achtabahn & kayef","achtvier","acid bath","acid ghost","acru","action bronson","action bronson & the alchemist","active gxng","adaam","adaam & vc barre","adam calhoun","adam jensen","adam lambert","adamlar","adam levine","adam mansbach","adam melchor","adam mickiewicz","adam sandler","adawa & shayiting el","addison rae","adekunle gold","adekunle gold & davido","adel","adel tawil","ademo","aden x asme","adf samski","adia victoria","adie (ph)","adi nowak","adin ross, kill jasper & tory lanez","aditi paul","адлин (adlin)","ados","adrian","adrianne lenker","adrianne lenker & buck meek","adriano celentano","adrienne rich","adult mom","adventure time","aesop rock","​aespa (에스파)","aew","af1","аффинаж (affinage band)","afi","aflacko","aflapoid","afn peso","afourteen","a-f-r-o","afroman","afroto","aftertheparty","aga b","​again&again","against me!","against the current","agalloch","agar agar","агата кристи (agata christie)","ag club","a. g. cook","agnes","agnes obel","agnetha fältskog","agnostic front","agust d","​a-ha","aha gazelle","ahiyan","ahmed santa","ahmet kaya","aidan martin","аигел (aigel)","⁣aikko","​aikko, inspace & katanacss","aileen quinn","aiman jr","aimee mann","aimer","air","the airborne toxic event","airon","air supply","air traffic controller","aitana","aitch","aitch & aj tracey","aiza seguerra","ajda pekkan","ajj","aj mitchell","aj tracey","ak","ak4:20","aka","akala","ak ausserkontrolle","akb48","akc kretta","akc misi",

#"скриптонит & райда (skriptonite & raida)","嵐 (arashi)","alex (칸첸알렉스) (kor)","​​alt-j","amy winehouse","andrew lloyd webber","atl","ayesha erotica","a1 x j1","a2h","a2m","a36","a4 (rus)","a92","ağaçkakan","aarne & lil krystalll","aaron cole","aaron keyes","aaron lewis","aaron may","aaron smith","aaron sorkin","aaron west & the roaring twenties","aaryan shah","ab6ix (에이비식스)","abbas bağırov","abbey glover","abby cates","abdullah siddiqui & talha anjum","abe parker","abhir hathi","abhi the nomad","abigail barlow","abo el anwar","aborted","above & beyond","aboveground germany","above the hood (grc)","above the law","abra","abra & boys noize","abra cadabra","abraham lincoln","abreu","abs-cbn music all-star","​absent","absofacto","żabson","ab-soul","abstract","abyusif","the acacia strain","the academic","aca lukas","acappella","accept","a.c.e","ace hood","ace of base","a.chal","achille lauro","achtabahn & kayef","achtvier","acid bath","acid ghost","acru","action bronson","action bronson & the alchemist","active gxng","adaam","adaam & vc barre","adam calhoun","adam jensen","adam lambert","adamlar","adam levine","adam mansbach","adam melchor","adam mickiewicz","adam sandler","adawa & shayiting el","addison rae","adekunle gold","adekunle gold & davido","adel","adel tawil","ademo","aden x asme","adf samski","adia victoria","adie (ph)","adi nowak","adin ross, kill jasper & tory lanez","aditi paul","адлин (adlin)","ados","adrian","adrianne lenker","adrianne lenker & buck meek","adriano celentano","adrienne rich","adult mom","adventure time","aesop rock","​aespa (에스파)","aew","af1","аффинаж (affinage band)","afi","aflacko","aflapoid","afn peso","afourteen","a-f-r-o","afroman","afroto","aftertheparty","aga b","​again&again","against me!","against the current","agalloch","agar agar","агата кристи (agata christie)","ag club","a. g. cook","agnes","agnes obel","agnetha fältskog","agnostic front","agust d","​a-ha","aha gazelle","ahiyan","ahmed santa","ahmet kaya","aidan martin","аигел (aigel)","⁣aikko","​aikko, inspace & katanacss","aileen quinn","aiman jr","aimee mann","aimer","air","the airborne toxic event","airon","air supply","air traffic controller","aitana","aitch","aitch & aj tracey","aiza seguerra","ajda pekkan","ajj","aj mitchell","aj tracey","ak","ak4:20","aka","akala","ak ausserkontrolle","akb48","akc kretta","akc misi","akhenaton","aki","akintoye","akinyele","akira the don","山岡晃 (akira yamaoka)","akmu (악뮤)","akua naru","a.l.a علاء","alabama","alabama 3","alabama shakes","alaina castillo","alan","alanis morissette","alan menken","alannah myles","the alan parsons project","alan walker","alan walker, k-391 & boy in space","alan walker, sabrina carpenter & farruko","alan watts","alaska thunderfuck","albert camus","albert hammond jr.","albertnbn","alberto grasu","alberto (pl)","альбина сексова (albina sexova)","albin lee meldau","alborosie","al bowlly","alces machlis","alcest","the alchemist","alcolirykoz","alcool club","​aldn","aldous harding","alejandro fernández","alejandro sanz","aleksandra prijović & lexington","aleksa safiya","alekseev","aleks syntek","あれくん (alekun)","alemán","алёна швец. (alena shvets.)","alesana","alesso","alesso & marshmello","alestorm","alexa demie","alexander 23","alexander o'neal","александр пистолетов (alexander pistoletov)","alexander rybak","alexandra savior","alex & sierra","alex cameron","alex ceesay","alex galagurskiy","alex gárgolas, mora & luar la l","alex isley","alexisonfire","alexis y fido","alex rose","alex rose & cnco","alex rose, rauw alejandro, lenny tavárez, cazzu & lyanno","alex turner","alex warren","alfaaz","alfa (ita)","alfie templeman","alf prøysen","alfred lord tennyson","algernon cadwallader","ali471","ali as","ali b","aliceband","alice cooper","alice longyu gao","alice merton","alice phoebe lou","alice walker","alicia awa","alicks","alien ant farm","alien weaponry","ali gatie","alireza jj","alisha chinai","alisha (rus)","alison krauss & union station","alison wonderland","alison yap","ali sorena","alizade","ali zafar","alizée","al jolson","alkaline","alkaline trio","alka yagnik","alkpote","all-4-one","allame","allan rayman","алла пугачёва (alla pugacheva)","allday","allen stone","alley gang","all good things","альянс (alliance) (rus)","allie x","alligatoah","alli neumann","allison russell","the allman brothers band","all nations music","all sons & daughters","all that remains","all them witches","almighty","aloe blacc","alonzo","alpha blondy","alphaville","alphavite","alpha wann","alpha wolf","al safir","al stewart","alz x 38","alt bloom","the altogether","żaluzja","alvaro soler","alvin & the chipmunks","alvin slaughter","alvintoday","alvvays","aly & aj","am","amaarae","amaarae & moliy","amalee","amanda fagan","amanda palmer","amanda seyfried","amandla stenberg","amaranthe","amarion","[amatory]","the amazing devil","the amazing world of gumball","ambar lucid","amber mark","amber run","ambré","ame bibabi","amee","ameer vann","amel bent","'amelie' original london cast","amel larrieux","amenra (cor)","america","american authors","american dad","american football","american murder song","american pleasure club","amerie","amici miei","amigo the devil","aminé","amirchik","amiri baraka","amir obè","amir tataloo","amit trivedi","the amity affliction","amo988","amon amarth","amorphis","amos lee","amp (any means possible)","amr diab","amrinder gill","şam (tr)","amuly","amy grant","amyl and the sniffers","amy macdonald","amy shark","anaal nathrakh","anacondaz","ana diaz","ana gabriel","anamanaguchi","anand raj anand","ana nikolić","anarbor","anaïs mitchell","anastacia","anastasia y.","anastasija","anathema","a. nayaka","anazed","anberlin","кисло-сладкий & bonah","​anders","anders matthesen","anderson .paak","хаски & масло черного тмина (husky & maslo chyornogo tmina)","andi","скриптонит & niman (scriptonite & niman)","and one","andré 3000","andréa burns","andraé crouch","andra day","andré de shields & hadestown original broadway company","andré de shields, reeve carney, jewelle blackman, yvette gonzalez-nacer, kay trinidad, timothy hughes, malcolm armwood, jessie shelton, kimberly marable, khaila wilcoxon, ahmad simmons, afra hines, t. oliver reid & john krause","andrea bocelli","andrea gibson","​​andreas odbjerg","андрей губин (andrei gubin)","​andrei, oscar, călinacho & amuly","andre nickatina","andrew belle","andrew bird","andrew e.","andrew gold","andrew lippa","andrew lloyd webber & carrie hope fletcher","andrew peterson","the andrews sisters","andrew stein","andrew w.k.","andré hazes","andro & andy panda","andro (ukr)","andrés (aparicio)","andy black","andy grammer","andy milonakis","andy mineo","andy mineo & wordsplayed","andy panda","andy shauf","andy williams","ane brun","anees","şanışer","anette olzon","angela carter","angela lansbury","angel du$t","angel haze","angelmaker","angelo de augustine","angel olsen","angels & airwaves","angels of light","angie stone","angèle","angus & julia stone","ani difranco","anikv","the animals","animal джаz","animaniacs","animus","anirudh ravichander","anita baker","anitta","ankhal","anıl piyancı","anna","anna akana","anna book","anna kendrick","anna nalick","anna puu","anne-marie","anne-marie & little mix","anne-marie & niall horan","anne-marie, ksi & digital farm animals","anne murray","annenmaykantereit","anne wilson","annie","annie dirusso","annie lennox","annie murphy","annihilator","ann marie","anonymous","anonymuz","盧瀚霆 (anson lo)","anson seabra","ansu","ant clemons","anth","anthem lights","anthony green","anthony hamilton","anthony ramos","anthony ramos, ariana debose, sasha hutchings, ephraim sykes, lin-manuel miranda & original broadway cast of \"hamilton\"","anthony ramos, corey hawkins, gregory diaz iv, noah catala, daphne rubin-vega, stephanie beatriz, dascha polanco & melissa barrera","anthony ramos, corey hawkins, melissa barrera, leslie grace, olga merediz, gregory diaz iv, noah catala, daphne rubin-vega, stephanie beatriz & dascha polanco","anthony ramos, lin-manuel miranda, jon rua, leslie odom, jr. & original broadway cast of \"hamilton\"","anthony ramos, okieriete onaodowan, daveed diggs, lin-manuel miranda & leslie odom jr.","anthrax","anti-flag","antilopen gang","antimatter","the antlers","antônio carlos jobim","антоха мс (antoha mc)","anton chekhov","antonello venditti","antonio aguilar","antony and the johnsons","antoon","antoon & big2","antti tuisku","ant wan","anuel aa & bad bunny","anuel aa & ozuna","anuel aa, ñengo flow, farruko, bad bunny, darell & casper mágico","anuv jain","the anxiety","apache 207","apashe","apashe & lubalin","apathy","ap dhillon","aphex twin","apocalipsa - אפוקליפסה","apocalyptica","apo hiking society","apparat","șapte","apulanta","aqtaii","aqua","the aquabats!","аквариум (aquarium)","aquilo","arab strap",

#["arash","嵐 (arashi) & r3hab","arca","arca & sia","arch enemy","architects","archive","archspire","arcángel","arcángel & bad bunny","ard adz","ardhito pramono","ardn","area21","a-reece","a-reece & jay jody and blue tape","ares","ariana grande & doja cat","ariana grande & justin bieber","ariana grande & nathan sykes","ariana grande & social house","ariana grande & the weeknd","ariana grande & victoria monét","arianne schreiber","ariel camacho y los plebes del rancho","ariel pink","ariel pink's haunted graffiti","ariel rivera","ariel winter","aries","ariete","arijit singh","arijit singh & mithoon","arik ancelin","ari lennox","ari lennox & j. cole","ария (ariya)","arizona zervas","arkells","ark patrol","arlo guthrie","arlo parks","armaan malik","armand hammer","armand hammer & the alchemist","the armed","armin van buuren","armin van buuren & davina michelle","ar'mon & trey","army of lovers","army of the pharaohs","aronchupa","a.r. rahman","arrdee","arrested development","arrested youth","arrogant worms","arsenal fc","arsenik","çağrı sinci","arz (uk)","art","артур эскейп (arthur escape)","arthur miller","arthur nery","arthur russell","articolo 31","artigeardit","artik & asti","art school girlfriend","arttu wiskari","arya lee","asaad (saudi money)","asaf avidan - אסף אבידן","asal kolaar x ofro","asammuell","asan","asanrap","a$ap ant","a$ap mob","asap science","a$ap twelvyy","asche","asche & kollegah","asha bhosle","ashafar","ashanti","ash b","ashcoolbro","ashe","ashe 22","ashe & finneas","asher roth","asheru","ash island","ashkidd","ashland craft","ashley cooke","ashton irwin","asia","asiah","asian doll","as i lay dying","asil slang","asin","as it is","асия (asiya)","asking alexandria","asme","aspova","assassin's creed sea shanties","astrid s","astro","astrud gilberto","the ataris","ateez","ateyaba","тяжёлая атлетика (athletic music)","ati242","atif aslam","atlantic starr","​atlas","atlas genius","atmosphere","ato","șatra b.e.n.z","atreyu","atsuover","atta boy","attack attack!","at the drive-in","attic abasement","attila","the aubreys","audio88 & yassin","audrey assad","audrey hepburn","audrey mika","audrey nuna","audrey nuna & niki","august","august alsina","august burns red","augustine","аукцыон (auktyon)","auli'i cravalho","au/ra","aurelio voltaire","auri","aurora","austin george","austin mahone","autem, bushido zho & 163onmyneck","autoheart","autumn!","av","the avalanches","avant","avantasia","avatar","avatar: the last airbender","avega","avelino","aventura & bad bunny","avery lynch","the avett brothers","aviators","avi(pl) x louis villain","aviva","a-wall","​awfultune","awkwafina","awolnation","axcx","axos","axwell λ ingrosso","aya nakamura","ayax","ayax y prok","ayo & teo","​ayokay","ayra starr","ayreon","ayushmann khurrana","ayzha nyree","az","azaan sami khan","azad","azahriah","azchike","azealia banks","azer bülbül","azet","azet & albi","azet & jugglerz","azizi gibson","azteca","azzi memo"]

#"baby keem & kendrick lamar","batuflex","big baby tape & kizaru","bladee","blanco","​​blink-182","bones","booba","brockhampton","b2k","the b-52's","babangida","babasónicos","babe rainbow","babes in toyland","babi","baby bash","baby bugs","babyface","babyface ray","baby gang","baby gho$t","baby k & alvaro soler","baby keem & travis scott","baby lullabies","baby mane","babymetal","baby queen","babysantana","baby smoove","baby tate","babytron","babyxsosa","bachman–turner overdrive","baci","the backseat lovers","backstreet boys","backxwash","the backyardigans","baco exu do blues","badbadnotgood","bad boy chiller crew","bad brains","bad bunny & jhay cortez","bad bunny & rosalía","bad bunny & tainy","bad bunny, jowell & randy & ñengo flow","​badchieff & cro","bad company","badcurt","badfinger","badflower","bad gyal","bad hop","bad meets evil","​badmómzjay","bad omens","bad religion","bad suns","bad wolves","baekhyun","bahamas","baha men","bahram","bailee madison","bakaprase","bakar","baker","balance and composure","bald dick","bali baby","ballout","ball park music","balthazar","balti بلطي","bambee","bambo the smuggler","bambu","bananarama","banda el recodo","bandalos chinos","banda ms de sergio lizárraga","the band camino","банд’эрос (band’eros)","bandmanrill","band of horses","the band perry","сметана band (smetana)","bane's world","baneva","the bangles","bankrol hayden","bankrol hayden & lil tecca","bankroll fresh","banks","banners","barack obama","barbara pravi","barbie","barbra streisand","bardero$","bardhi","bardhi & azet","barlow & bear","barış manço","barney","barns courtney","baroness","barrington levy","barry jhay","barry louis polisar","barry manilow","barry white","bars and melody","bart baker","bartees strange","bas","baseboys","basement","basil valdez","basshunter","bassi maestro","bass santana","баста (basta)","баста и гуф (basta & guf)","bastille","bat for lashes","bathory","baths","batuflex & cakal","batuflex, uzi, lvbel c5 & critical","батюшка (batushka)","bauhaus","bôa (uk)","bausa","baxter dury","bay faction","bayside","bazanji","bazart","baz luhrmann","bazooka","bb beats","b.b. king","​bbno$","​bbno$ & diamond pistols","bby goyard","​bbymutha","bức tường","​beabadoobee","beach bunny","beach fossils","beach goons","beach house","beach weather","bea miller","beanie sigel","bear ghost","bearings","bear mccreary","bear's den","bears in trees","beartooth","beast coast","beast in black","beautiful eulogy","the beautiful south","beba","beck","becky g","becky hill","becky hill & david guetta","bedoes","bedoes & kubi producent","bedoes & lanek","bedroom","​bedwetter","beenie man","beetlebug","be:first","bege","behemoth","behm","being as an ocean","beirut","bekrija","belinda carlisle","bella poarch","bella shmurda","bell biv devoe","belle and sebastian","bello figo","belly","belly & the weeknd","belly, the weeknd & young thug","belmondo","belmont","the belonging co","be more chill ensemble","benab","ben&ben","ben bailey smith","ben böhmer","ben caplan","​benedixhion","benee","ben e. king","ben fero","ben folds","ben folds five","ben howard","benjamin amaru","benjamin hav","benjamin ingrosso","benjamin tod","ben kessler & lizzy mcalpine","​benny blanco & juice wrld","​benny blanco, halsey & khalid","benny dayal","benny jamz, gilli & kesi","benny the butcher","benny the butcher & harry fraud","ben platt","ben platt & laura dreyfuss","ben platt & original broadway cast of dear evan hansen","ben platt, kristolyn lloyd, will rolland, laura dreyfuss & original broadway cast of dear evan hansen","ben rector","beny jr","beny jr & el guincho","beogradski sindikat","beowulf","beres hammond","bernadette peters","berner","berried alive","ber (uk)","bessie smith","bet","beta","beteo","bethany barnard","bethel music","beth hart","the beths","beton.hofi","bette midler","better oblivion community center","betty","between friends","between the buried and me","bexey","beyazz","beyoncé, jay-z & childish gambino","beyond","bezczel","bfb da packman","b.g.","bhad bhabie","bhz","böhse onkelz","b.i","białas","białas & lanek","białas & white 2115","bibi (비비)","bibič (pl)","bic fizzle","biddl3","biffy clyro","big ant dog","bigbabygucci","big baby tape","bigbang (빅뱅)","big black","big boi","big boogie","big daddy kane","big data","bigflo & oli","biggie cheese","big homiie g","bigkaybeezy","big k.r.i.t.","big l","big pun","big red machine","bigru i paja kratak","big russian boss","bigsam (palestine)","big scarr","big sean & metro boomin","big shaq","big soto","big star","big thief","big time rush","big tymers","bigwalkdog","big wild","big yavo","big zulu","biig piig","bijelo dugme","bikini kill","билик (bilik)","bill callahan","billie eilish & khalid","billie holiday","billie marten","bill withers","bill wurtz","billy bragg","billy bragg and wilco","billy cobb","billy idol","billy joe shaver","billy marchiafava","billy milligan","billy ocean","billy porter","billy squier","billy straus","billy strings","billy talent","​billy woods","​billy woods & ​kenny segal","bilmuri","bin","bing crosby","binki","bino rideaux","bino rideaux & roddy ricch","bin, pl quest & mainstreet records","birdman","birdman & lil wayne","birds of tokyo","birdtalker","birdy","birdy + rhodes","the birthday massacre","the birthday party","bishop briggs","bishop bullwinkle","bisz","biting elbows","bittuev","biv","bixi blake","bizarrap & chucky73","bizarrap & eladio carrión","bizarrap & mhd","bizarrap & snow tha product","biz markie",
#"bizzle","bizzy banks","bizzy bone","bj putnam","björk","björn afzelius","björn rosenström","bj the chicago kid","bk'","bktherula","blacha","black","blackalicious","the black angels","black atlass","​blackbear","black country, new road","the black crowes","black dresses","black eyed peas","black flag","black gryph0n & baasik","black hippy","black label society","black lace","blacklite district","black m","black marble","​black midi","black moon","blackmore's night","blackpink & selena gomez","black pumas","black rebel motorcycle club","black sea dahu","black sheep","the black skirts","black star","blackstreet","black thought","black veil brides","blackwave.","​blackwinterwells","blac youngsta","bladee & ecco2k","bladee & mechatok","bladee & thaiboy digital","bladee, ecco2k & thaiboy digital","​blago white","blake rose","blanco & sfera ebbasta","blanco (uk)","blanks","blaqbonez","blaq diamond","the blasting company","блэйзер (blayzer)","blaze foley","bl@ckbox","blckk","bleachers","blessd, javiielo & neutro shorty","​blessthefall","bløf","blind channel","blind faith","blind guardian","blind melon","blisofly","bliss n eso","blixemi","blocboy jb","block 6","bloc party","blonde redhead","blondie","bloodhound gang","blood on the dance floor","blood orange","bloody hawk","blossoms","b lovee","​bülow","blu","blu & exile","blue","bluebucksclan","blueface","blueface & og bobby billions","blue foundation","blue ivy, saint jhn, beyoncé & wizkid","blue october","the blues brothers","blue's clues","blue stahli","the blue stones","blues traveler","blue swede","blue virus","blue öyster cult","bluprint (girl group)","blur","blxckie","blxst & bino rideaux","blxst & tyga","b-mike","​bnkr44","​bnkr44 x psicologi","boa (보아)","boards of canada","b.o.b","bobbie gentry","bobby 2 pistolz","bobby brown","bobby caldwell","bobby darin","bobby hebb","bobby mcferrin","bobby raps","bobby shmurda","bobby vinton","bobby womack","bob dylan & the band","bober","bob marley & the wailers","bob's burgers","bob schneider","bob sinclar","bob the builder","bodiev","body count","boef","​bo en","bohemia","bohnes","bojack horseman","bojan","bol4","boldy james & the alchemist","​​bollywoodfm","bolémvn","bomba estéreo","bombay bicycle club","bombay jayashree","bombay vikings","bomb the music industry!","bomfunk mc's","bones & eddy baker","bone thugs-n-harmony","bonez mc","bonez mc & raf camora","bong da city (grc)","bon iver","bon iver & st. vincent","bonnie \"prince\" billy","bonnie raitt","bonnie tyler","bonus rpk","boofpaxkmooky","boogie down productions","boohle","booka600","booker","booker, мукка (mukka) & pyrokinesis","booking machine","the books","бумбокс (boombox) (rus)","the boomtown rats","the boondocks","boosie badazz","born of osiris","born without bones","bosh","bosse","bossikan & ricta & fly lo","bossikan (grc)","boston","boston manor","boulevard depo","boulevard depo & i61","boulevard depo & jeembo","boulevard depo & sp4k","bowling for soup","bow wow","box car racer","boy fantasy","boy froot & lil peep","​boygenius","boy harsher","boyinaband","boyish","​boylife","​boy pablo","the boyz","boyz ii men","boys like girls","boys who cry (spongebob)","boys world","boywithuke","boz scaggs","b praak","brad knauber","the brady bunch","i̇brahim tatlıses","​brakence","branco","brandi carlile","brand new","brand of sacrifice","brandon flowers","brandon lake","brandon rogers","brandy","brandy & monica","branya","branya & macan","bratty","the brave little abacus","bravo the bagchaser","braxton knight","b ray (vnm)","brazil national football team","bread","breakbot","breakup shoes","the breeders","bree runway","brenda lee","brennan savage","brent faiyaz & dj dahi","brent morgan","bresh","brian & jenn johnson","brian david gilbert","brian doerksen","brian eno","the brian jonestown massacre","brian mcknight","brick bazuka","brick + mortar","the bridge city sinners","bridgit mendler","bright eyes","bring it on: the musical - original broadway cast","bris","briston maroney","britnee kellogg","brittany howard","brittnee belt","børns","broadcast","broadway karkat","the brobecks","brocasito","brodha v","broederliefde","broilers","broken bells","broken social scene","bronski beat","broods","the brook & the bluff","brooke candy","the brooklyn tabernacle choir","brotha lynch hung","brother ali","brothers of metal","brothers osborne","brown bird","brownman revival","brs kash, dababy & city girls","bru-c","bruhmanegod","brulux","bruno coulais","bruno major","brut","брутто (brutto)","brxxk","bryan adams","bryan ferry","bryant myers","bryce fox","bryce pinkham","brye","brymo","bryson gray","brzo trči ljanmi & inas","btob","buba corelli","bubba sparxxx","buckcherry","buddy castle","budman.","buena vista social club","буерак (buerak)","buffalo springfield","buffy sainte-marie","buggles","b.u.g. mafia","bugoy na koykoy","bugzy malone","buhodermia 夜","built to spill","buju","buju banton","bu kolthoum","bully (nld)","bumble beezy","bumble beezy & roux","bun b","buni","bunny girl","buntai","burgos","burhan g","burial","burna bandz","burna boy","burning spear",