artists = [
'Logic',
'Rihanna',
'Frank Sinatra',
'The Beatles',
'Bob Dylan',
'Elvis Presley',
'Rolling Stones',
'Chuck Berry',
'Jimi Hendrix',
'James Brown',
'Little Richard',
'Aretha Franklin',
'Ray Charles',
'Bob Marley',
'The Beach Boys',
'Buddy Holly',
'Led Zeppelin',
'Stevie Wonder',
'Sam Cooke',
'Muddy Waters',
'Marvin Gaye',
'The Velvet Underground',
'Bo Diddley',
'Otis Redding',
'U2',
'Bruce Springsteen',
'Jerry Lee Lewis',
'Fats Domino',
'The Ramones',
'Nirvana',
'Prince',
'The Who',
'The Clash',
'Johnny Cash',
'Smokey Robinson & The Miracles',
'The Everly Brothers',
'Neil Young',
'Michael Jackson',
'Madonna',
'Roy Orbison',
'John Lennon',
'David Bowie',
'Simon and Garfunkel',
'The Doors',
'Van Morrison',
'Sly and the Family Stone',
'Public Enemy',
'The Byrds',
'Janis Joplin',
'Patti Smith',
'Run-DMC',
'Elton John',
'The Band',
'Howlin Wolf',
'Allman Brothers Band',
'Eric Clapton',
'Dr. Dre',
'Grateful Dead',
'Parliament Funkadelic',
'Aerosmith',
'Sex Pistols',
'Louis Jordan',
'Joni Mitchell',
'Tina Turner',
'Etta James',
'Phil Spector',
'The Kinks',
'Al Green',
'Cream',
'The Temptations',
'Jackie Wilson',
'Carl Perkins',
'The Police',
'Frank Zappa',
'AC/DC',
'Radiohead',
'Hank Williams',
'The Eagles',
'The Shirelles',
'Beastie Boys',
'The Stooges',
'The Four Tops',
'Elvis Costello',
'The Drifters',
'Eminem',
'N.W.A.',
'James Taylor',
'Black Sabbath',
'Tupac Shakur',
'Gram Parsons',
'Miles Davis',
'The Yardbirds',
'Carlos Santana',
'Ricky Nelson',
'Guns n Roses',
'Booker T. and the MG',
'Nine Inch Nails',
'Lynyrd Skynyrd',
'Martha and the Vandellas',
'Diana Ross and the Supremes',
'Roxy Music',
'Curtis Mayfield',
'Lee Scratch Perry'
'Linkin Park',
'Avenged Sevenfold',
'Green Day',
'Snow Patrol',
'Korn',
'Nickelback',
'Slipknot',
'Fall Out Boy',
'System of a Down',
'Blink-182',
'Creed',
'Radiohead',
'Killswitch Engage',
'Coldplay',
'Disturbed',
'The Click Five',
'Porcupine Tree',
'Foo Fighters',
'Underoath',
'Audioslave',
'Papa Roach',
'Sum 41',
'Bullet For My Valentine',
'Tool',
'The Strokes',
'Weezer',
'Limp Bizkit',
'My Chemical Romance',
'Trivium',
'Animal Collective',
'Lifehouse',
'Deftones',
'Godsmack',
'Bon Jovi',
'Alter Bridge',
'Nine Inch Nails',
'Good Charlotte',
'Modest Mouse',
'Franz Ferdinand',
'Meshuggah',
'Drowning Pool',
'Switchfoot',
'Death Cab For Cutie',
'Jimmy Eat World',
'The Offspring',
'Interpol',
'Kings of Leon',
'The Bravery',
'Puddle of Mudd',
'Stained',
'The Black Keys',
'Muse',
'Breaking Benjamin',
'30 Seconds To Mars',
'U2',
'Hoobastank',
'New Found Glory',
'Evanescence',
'Yeah Yeah Yeahs',
'Seether',
'The Killers',
'Wiclo',
'Paramore',
'Our Lady Peace',
'Maroon 5',
'Queens of the Stone Age',
'LCD Soundsystem',
'Pearl Jam',
'Simple Plan',
'The Hives',
'Metallica',
'Arctic Monkeys',
'Red Hot Chili Peppers',
'The All-American Rejects',
'Shinedown',
'Rilo Kiley',
'Coheed and Cambria',
'The Vines',
'Skillet',
'Aerosmith',
'The Mars Volta',
'Shadows Fall',
'Daughtry',
'The Fray',
'The Black Dahlia Murder',
'Kaiser Chiefs',
'Incubus',
'AC/DC',
'Arcade Fire',
'Lamb of God',
'Opeth',
'Spoon',
'Nightwish',
'Dream Theater',
'Mastadon',
'Barenaked Ladies',
'Symphony X',
'Three Days Grace',
'The Von Bondies',
'Hatebreed',
'Olivia Rodrigo',
'Taylor Swift',
'Eminem',
'Juice WRLD',
'Drake',
'Ed Sheeran',
'J. Cole',
'Ariana Grande',
'Kanye West',
'Justin Bieber',
'Lana Del Rey',
'Billie Eilish',
'Julia Michaels',
'The Weeknd',
'Kendrick Lamar',
'BTS',
'Cardi B',
'Travis Scott',
'Lady Gaga',
'Mariah Carey',
'John Legend',
'Justin Timerlake',
'Usher',
'Beyoncé',
'Pharrell Williams',
'Alicia Keys',
'Kelly Clarkson',
'Katy Perry',
'Adele',
'Akon',
'Bruno Mars',
'Selena Gomez',
'Khalid',
'Imagine Dragons',
'One Direction',
'James TW',
'Lewis Capaldi',
'Lauv',
'Maisie Peters',
'Alec Benjamin',
'Lorde',
'James Arthur',
'Dean Lewis',
'Jacob Lee',
'Calum Scott',
'Troye Sivan',
'Passenger',
'John Mayer',
'James Bay',
'Sam Smith',
'Shawn Mendes'
]

artists2 = ['youngboy never broke again','lil nas x','doja cat','lil baby','morgan wallen','rod wave','bad bunny','future','post malone','pop smoke','polo g','luke combs','lil uzi vert','lil durk','trippie redd','$uicideboy$','lil wayne','moneybagg yo','xxxtentacion','mac miller','the kid laroi','dababy','gunna','kevin gates','jack harlow','chris stapleton','tyler, the creator','jason aldean','chris brown','playboi carti','kodak black','megan thee stallion','dua lipa','a boogie wit da hoodie','g-eazy','young thug','meek mill','machine gun kelly','j. balvin','nf','baby keem','migos','luke bryan','nicki minaj','glass animals','lil tecca','halsey','thomas rhett','harry styles','fleetwood mac','kane brown','kid cudi','florida georgia line','queen','roddy ricch','dj khaled','21 savage','jhené aiko','lil peep','frank ocean','sleepy hallow','ynw melly','lil tjay','giveon','twenty one pilots','h.e.r','kacey musgraves','king von','blackbear','dan + shay','rauw alejandro','eslabon armado','eric church','george strait','2pac','tyler childers','pooh shiesty','kenny chesney','eagles','miley cyrus','blake shelton','russ','jay-z','sza','panic! at the disco','grupo firme','gucci mane','walker hayes','sam hunt','lee brice','42 dugg','the neighbourhood','tory lanez','the rolling stones','brent faiyaz','zac brown band','metro boomin','p!nk','nle choppa','summer walker','farruko','ozuna','kehlani','the lumineers','g herbo','a$ap rocky','karol g','wiz khalifa','miranda lambert','carrie underwood','maluma','joyner lucas','tom petty','onerepublic','notorious b.i.g.','big sean','est gee','joji','marshmello','bryson tiller','pitbull','jelly roll','tim mcgraw','old dominion','pink floyd','cody johnson','wizkid','childish gambino','five finger death punch','ajr','alan jackson','jonas brothers','upchurch','young dolph','original broadway cast of hamilton','calvin harris','jordan davis','billy joel','don toliver','50 cent','jon pardi','nelly','mo3',"guns n' roses",'anuel aa','big30','ski mask the slump god','marca mp','bo burnham','willow','creedence clearwater revival','gorillaz','lizzo','melanie martinez','maren morris','brooks & dunn','daddy yankee','aventura','tame impala','6lack','key glock','jason derulo','the chainsmokers','britney spears','nocap','camila cabello','demi lovato','trey songz','partynextdoor','iann dior','myke towers','dierks bentley','journey','cage the elephant','chris young','miguel','brantley gilbert','t.i.','elevation worship','justin timberlake','outkast','jack johnson','tee grizzley','hozier','keith urban','romeo santos','junior h','5 seconds of summer','tyga','jhay cortez','yung bleu','alessia cara','mitski','young jeezy','dustin lynch','kali uchis','nipsey hussle','sheff g','nav','cocomelon','måneskin','westside gunn','clairo','brett young','sublime','earth wind & fire','money man','jeremih','24kgoldn','christian nodal','greta van fleet','chief keef','2 chainz','ty dolla $ign','nas','toby keith','van halen','conan gray','tate mcrae','david guetta','el fantasma','shakira','t-pain','lil yachty','natanael cano','the black eyed peas','flo rida','calibre 50','parker mccollum','cole swindell','lauren daigle','saweetie','ne-yo','cody jinks','kelsea ballerini','banda sinaloense ms de sergio lizárraga','oliver tree','toosii','koe wetzel','bob marley, the wailers','gabby barrett','lil skies','michael bublé','steve lacy','garth brooks','rascal flatts','young nudy','bazzi','toby fox','riley green','tai verdes','jake owen','$not','mac demarco','wale','daryl hall, john oates','bring me the horizon','hardy','bebe rexha','rick ross','bee gees','zach bryan','schoolboy q','yo gotti','snoop dogg','bia','avicii','girl in red','cavetown','ella mai','ke$ha','luis r. conriquez','isaiah rashad','sech','los dos carnales','surfaces','rex orange county','yg','bob seger','sia','daniel caesar','pinkpantheress','whitney houston','lady a','mary j. blige','masked wolf','carin leon','lord huron','abba','los tucanes de tijuana','little big town','kid rock','mozzy','enya','darius rucker','brad paisley','alice in chains','justin moore','aaliyah','hillsong worship','mitchell tenpenny','carly pearce','enrique iglesias','shoreline mafia','billy currington','hank williams jr.','saint jhn','train','jazmine sullivan','mötley crüe','maverick city music','don omar','def leppard','chance the rapper','vance joy',"destiny's child",'chase atlantic','all time low','phil collins','diplo','ice cube','phoebe bridgers','tink','meghan trainor','yfn lucci','lil mosey','k camp','normani','3 doors down','colter wall','dj snake','los bukis','tech n9ne','lany','dmx','ava max','rae sremmurd','daft punk','los tigres del norte','city girls','chlöe','chase rice','nicky jam','jaydayoungan','selena','charlie puth','whiskey myers','a$ap ferg','foster the people','tones and i','hillsong united','silk sonic','ckay','sleepy john','mother mother','r. kelly','scotty mccreery','lainey wilson','smashing pumpkins','queen naija','vicente fernández','fetty wap','ellie goulding','kygo','lil darkie','comethazine','mumford & sons','vedo','ozzy osbourne','blackpink','ciara','yeat','a day to remember','fredo bang','avril lavigne','tom macdonald','casting crowns','niko moon','falling in reverse','los temerarios','ashnikko',"pi'erre bourne",'leon bridges','larry june','boney m.','steely dan','ryan hurd','sturgill simpson','bryce vine','willie nelson','jacquees','french montana','stray kids','blxst','jennifer lopez','needtobreathe','the chicks','alina baraz','quinn xcii']

#"alex (칸첸알렉스) (kor)","​​alt-j","amy winehouse","andrew lloyd webber","скриптонит & райда (skriptonite & raida)","嵐 (arashi)","atl","ayesha erotica","a1 x j1","a2h","a2m","a36","a4 (rus)","a92","ağaçkakan","aarne & lil krystalll","aaron cole","aaron keyes","aaron lewis","aaron may","aaron smith","aaron sorkin","aaron west & the roaring twenties","aaryan shah","ab6ix (에이비식스)","abbas bağırov","abbey glover","abby cates","abdullah siddiqui & talha anjum","abe parker","abhir hathi","abhi the nomad","abigail barlow","abo el anwar","aborted","above & beyond","aboveground germany","above the hood (grc)","above the law","abra","abra & boys noize","abra cadabra","abraham lincoln","abreu","abs-cbn music all-star","​absent","absofacto","żabson","ab-soul","abstract","abyusif","the acacia strain","the academic","aca lukas","acappella","accept","a.c.e","ace hood","ace of base","a.chal","achille lauro","achtabahn & kayef","achtvier","acid bath","acid ghost","acru","action bronson","action bronson & the alchemist","active gxng","adaam","adaam & vc barre","adam calhoun","adam jensen","adam lambert","adamlar","adam levine","adam mansbach","adam melchor","adam mickiewicz","adam sandler","adawa & shayiting el","addison rae","adekunle gold","adekunle gold & davido","adel","adel tawil","ademo","aden x asme","adf samski","adia victoria","adie (ph)","adi nowak","adin ross, kill jasper & tory lanez","aditi paul","адлин (adlin)","ados","adrian","adrianne lenker","adrianne lenker & buck meek","adriano celentano","adrienne rich","adult mom","adventure time","aesop rock","​aespa (에스파)","aew","af1","аффинаж (affinage band)","afi","aflacko","aflapoid","afn peso","afourteen","a-f-r-o","afroman","afroto","aftertheparty","aga b","​again&again","against me!","against the current","agalloch","agar agar","агата кристи (agata christie)","ag club","a. g. cook","agnes","agnes obel","agnetha fältskog","agnostic front","agust d","​a-ha","aha gazelle","ahiyan","ahmed santa","ahmet kaya","aidan martin","аигел (aigel)","⁣aikko","​aikko, inspace & katanacss","aileen quinn","aiman jr","aimee mann","aimer","air","the airborne toxic event","airon","air supply","air traffic controller","aitana","aitch","aitch & aj tracey","aiza seguerra","ajda pekkan","ajj","aj mitchell","aj tracey","ak","ak4:20","aka","akala","ak ausserkontrolle","akb48","akc kretta","akc misi",

#"скриптонит & райда (skriptonite & raida)","嵐 (arashi)","alex (칸첸알렉스) (kor)","​​alt-j","amy winehouse","andrew lloyd webber","atl","ayesha erotica","a1 x j1","a2h","a2m","a36","a4 (rus)","a92","ağaçkakan","aarne & lil krystalll","aaron cole","aaron keyes","aaron lewis","aaron may","aaron smith","aaron sorkin","aaron west & the roaring twenties","aaryan shah","ab6ix (에이비식스)","abbas bağırov","abbey glover","abby cates","abdullah siddiqui & talha anjum","abe parker","abhir hathi","abhi the nomad","abigail barlow","abo el anwar","aborted","above & beyond","aboveground germany","above the hood (grc)","above the law","abra","abra & boys noize","abra cadabra","abraham lincoln","abreu","abs-cbn music all-star","​absent","absofacto","żabson","ab-soul","abstract","abyusif","the acacia strain","the academic","aca lukas","acappella","accept","a.c.e","ace hood","ace of base","a.chal","achille lauro","achtabahn & kayef","achtvier","acid bath","acid ghost","acru","action bronson","action bronson & the alchemist","active gxng","adaam","adaam & vc barre","adam calhoun","adam jensen","adam lambert","adamlar","adam levine","adam mansbach","adam melchor","adam mickiewicz","adam sandler","adawa & shayiting el","addison rae","adekunle gold","adekunle gold & davido","adel","adel tawil","ademo","aden x asme","adf samski","adia victoria","adie (ph)","adi nowak","adin ross, kill jasper & tory lanez","aditi paul","адлин (adlin)","ados","adrian","adrianne lenker","adrianne lenker & buck meek","adriano celentano","adrienne rich","adult mom","adventure time","aesop rock","​aespa (에스파)","aew","af1","аффинаж (affinage band)","afi","aflacko","aflapoid","afn peso","afourteen","a-f-r-o","afroman","afroto","aftertheparty","aga b","​again&again","against me!","against the current","agalloch","agar agar","агата кристи (agata christie)","ag club","a. g. cook","agnes","agnes obel","agnetha fältskog","agnostic front","agust d","​a-ha","aha gazelle","ahiyan","ahmed santa","ahmet kaya","aidan martin","аигел (aigel)","⁣aikko","​aikko, inspace & katanacss","aileen quinn","aiman jr","aimee mann","aimer","air","the airborne toxic event","airon","air supply","air traffic controller","aitana","aitch","aitch & aj tracey","aiza seguerra","ajda pekkan","ajj","aj mitchell","aj tracey","ak","ak4:20","aka","akala","ak ausserkontrolle","akb48","akc kretta","akc misi","akhenaton","aki","akintoye","akinyele","akira the don","山岡晃 (akira yamaoka)","akmu (악뮤)","akua naru","a.l.a علاء","alabama","alabama 3","alabama shakes","alaina castillo","alan","alanis morissette","alan menken","alannah myles","the alan parsons project","alan walker","alan walker, k-391 & boy in space","alan walker, sabrina carpenter & farruko","alan watts","alaska thunderfuck","albert camus","albert hammond jr.","albertnbn","alberto grasu","alberto (pl)","альбина сексова (albina sexova)","albin lee meldau","alborosie","al bowlly","alces machlis","alcest","the alchemist","alcolirykoz","alcool club","​aldn","aldous harding","alejandro fernández","alejandro sanz","aleksandra prijović & lexington","aleksa safiya","alekseev","aleks syntek","あれくん (alekun)","alemán","алёна швец. (alena shvets.)","alesana","alesso","alesso & marshmello","alestorm","alexa demie","alexander 23","alexander o'neal","александр пистолетов (alexander pistoletov)","alexander rybak","alexandra savior","alex & sierra","alex cameron","alex ceesay","alex galagurskiy","alex gárgolas, mora & luar la l","alex isley","alexisonfire","alexis y fido","alex rose","alex rose & cnco","alex rose, rauw alejandro, lenny tavárez, cazzu & lyanno","alex turner","alex warren","alfaaz","alfa (ita)","alfie templeman","alf prøysen","alfred lord tennyson","algernon cadwallader","ali471","ali as","ali b","aliceband","alice cooper","alice longyu gao","alice merton","alice phoebe lou","alice walker","alicia awa","alicks","alien ant farm","alien weaponry","ali gatie","alireza jj","alisha chinai","alisha (rus)","alison krauss & union station","alison wonderland","alison yap","ali sorena","alizade","ali zafar","alizée","al jolson","alkaline","alkaline trio","alka yagnik","alkpote","all-4-one","allame","allan rayman","алла пугачёва (alla pugacheva)","allday","allen stone","alley gang","all good things","альянс (alliance) (rus)","allie x","alligatoah","alli neumann","allison russell","the allman brothers band","all nations music","all sons & daughters","all that remains","all them witches","almighty","aloe blacc","alonzo","alpha blondy","alphaville","alphavite","alpha wann","alpha wolf","al safir","al stewart","alz x 38","alt bloom","the altogether","żaluzja","alvaro soler","alvin & the chipmunks","alvin slaughter","alvintoday","alvvays","aly & aj","am","amaarae","amaarae & moliy","amalee","amanda fagan","amanda palmer","amanda seyfried","amandla stenberg","amaranthe","amarion","[amatory]","the amazing devil","the amazing world of gumball","ambar lucid","amber mark","amber run","ambré","ame bibabi","amee","ameer vann","amel bent","'amelie' original london cast","amel larrieux","amenra (cor)","america","american authors","american dad","american football","american murder song","american pleasure club","amerie","amici miei","amigo the devil","aminé","amirchik","amiri baraka","amir obè","amir tataloo","amit trivedi","the amity affliction","amo988","amon amarth","amorphis","amos lee","amp (any means possible)","amr diab","amrinder gill","şam (tr)","amuly","amy grant","amyl and the sniffers","amy macdonald","amy shark","anaal nathrakh","anacondaz","ana diaz","ana gabriel","anamanaguchi","anand raj anand","ana nikolić","anarbor","anaïs mitchell","anastacia","anastasia y.","anastasija","anathema","a. nayaka","anazed","anberlin","кисло-сладкий & bonah","​anders","anders matthesen","anderson .paak","хаски & масло черного тмина (husky & maslo chyornogo tmina)","andi","скриптонит & niman (scriptonite & niman)","and one","andré 3000","andréa burns","andraé crouch","andra day","andré de shields & hadestown original broadway company","andré de shields, reeve carney, jewelle blackman, yvette gonzalez-nacer, kay trinidad, timothy hughes, malcolm armwood, jessie shelton, kimberly marable, khaila wilcoxon, ahmad simmons, afra hines, t. oliver reid & john krause","andrea bocelli","andrea gibson","​​andreas odbjerg","андрей губин (andrei gubin)","​andrei, oscar, călinacho & amuly","andre nickatina","andrew belle","andrew bird","andrew e.","andrew gold","andrew lippa","andrew lloyd webber & carrie hope fletcher","andrew peterson","the andrews sisters","andrew stein","andrew w.k.","andré hazes","andro & andy panda","andro (ukr)","andrés (aparicio)","andy black","andy grammer","andy milonakis","andy mineo","andy mineo & wordsplayed","andy panda","andy shauf","andy williams","ane brun","anees","şanışer","anette olzon","angela carter","angela lansbury","angel du$t","angel haze","angelmaker","angelo de augustine","angel olsen","angels & airwaves","angels of light","angie stone","angèle","angus & julia stone","ani difranco","anikv","the animals","animal джаz","animaniacs","animus","anirudh ravichander","anita baker","anitta","ankhal","anıl piyancı","anna","anna akana","anna book","anna kendrick","anna nalick","anna puu","anne-marie","anne-marie & little mix","anne-marie & niall horan","anne-marie, ksi & digital farm animals","anne murray","annenmaykantereit","anne wilson","annie","annie dirusso","annie lennox","annie murphy","annihilator","ann marie","anonymous","anonymuz","盧瀚霆 (anson lo)","anson seabra","ansu","ant clemons","anth","anthem lights","anthony green","anthony hamilton","anthony ramos","anthony ramos, ariana debose, sasha hutchings, ephraim sykes, lin-manuel miranda & original broadway cast of \"hamilton\"","anthony ramos, corey hawkins, gregory diaz iv, noah catala, daphne rubin-vega, stephanie beatriz, dascha polanco & melissa barrera","anthony ramos, corey hawkins, melissa barrera, leslie grace, olga merediz, gregory diaz iv, noah catala, daphne rubin-vega, stephanie beatriz & dascha polanco","anthony ramos, lin-manuel miranda, jon rua, leslie odom, jr. & original broadway cast of \"hamilton\"","anthony ramos, okieriete onaodowan, daveed diggs, lin-manuel miranda & leslie odom jr.","anthrax","anti-flag","antilopen gang","antimatter","the antlers","antônio carlos jobim","антоха мс (antoha mc)","anton chekhov","antonello venditti","antonio aguilar","antony and the johnsons","antoon","antoon & big2","antti tuisku","ant wan","anuel aa & bad bunny","anuel aa & ozuna","anuel aa, ñengo flow, farruko, bad bunny, darell & casper mágico","anuv jain","the anxiety","apache 207","apashe","apashe & lubalin","apathy","ap dhillon","aphex twin","apocalipsa - אפוקליפסה","apocalyptica","apo hiking society","apparat","șapte","apulanta","aqtaii","aqua","the aquabats!","аквариум (aquarium)","aquilo","arab strap",