import lyricsgenius as lg # https://github.com/johnwmillr/LyricsGenius


file = open("/mnt/f/lyrics_collection/all_songs_2.txt", "w")  # File to write lyrics to
genius = lg.Genius('aTh-Dc2WaOTlLdHP5p7xV_YpLke-MQvY9Ux_nfg68IcGikRld8yJZfIwSv6794L1',  # Client access token from Genius Client API page
                             skip_non_songs=True, excluded_terms=["(Remix)", "(Live)"],
                             remove_section_headers=True, timeout=30)

artists = [
# 'Logic',
# 'Rihanna',
# 'Frank Sinatra',
# 'The Beatles',
# 'Bob Dylan',
# 'Elvis Presley',
# 'Rolling Stones',
# 'Chuck Berry',
# 'Jimi Hendrix',
# 'James Brown',
# 'Little Richard',
# 'Aretha Franklin',
# 'Ray Charles',
# 'Bob Marley',
# 'The Beach Boys',
# 'Buddy Holly',
# 'Led Zeppelin',
# 'Stevie Wonder',
# 'Sam Cooke',
# 'Muddy Waters',
# 'Marvin Gaye',
# 'The Velvet Underground',
# 'Bo Diddley',
# 'Otis Redding',
# 'U2',
# 'Bruce Springsteen',
# 'Jerry Lee Lewis',
# 'Fats Domino',
# 'The Ramones',
# 'Nirvana',
# 'Prince',
# 'The Who',
# 'The Clash',
# 'Johnny Cash',
# 'Smokey Robinson & The Miracles',
# 'The Everly Brothers',
# 'Neil Young',
# 'Michael Jackson',
# 'Madonna',
# 'Roy Orbison',
# 'John Lennon',
# 'David Bowie',
# 'Simon and Garfunkel',
# 'The Doors',
# 'Van Morrison',
# 'Sly and the Family Stone',
# 'Public Enemy',
# 'The Byrds',
# 'Janis Joplin',
# 'Patti Smith',
# 'Run-DMC',
# 'Elton John',
# 'The Band',
# 'Howlin Wolf',
# 'Allman Brothers Band',
# 'Eric Clapton',
# 'Dr. Dre',
# 'Grateful Dead',
# 'Parliament Funkadelic',
# 'Aerosmith',
# 'Sex Pistols',
# 'Louis Jordan',
# 'Joni Mitchell',
# 'Tina Turner',
# 'Etta James',
# 'Phil Spector',
# 'The Kinks',
# 'Al Green',
# 'Cream',
# 'The Temptations',
# 'Jackie Wilson',
# 'Carl Perkins',
# 'The Police',
# 'Frank Zappa',
# 'AC/DC',
# 'Radiohead',
# 'Hank Williams',
# 'The Eagles',
# 'The Shirelles',
# 'Beastie Boys',
# 'The Stooges',
# 'The Four Tops',
# 'Elvis Costello',
# 'The Drifters',
# 'Eminem',
# 'N.W.A.',
# 'James Taylor',
# 'Black Sabbath',
# 'Tupac Shakur',
# 'Gram Parsons',
# 'Miles Davis',
# 'The Yardbirds',
# 'Carlos Santana',
# 'Ricky Nelson',
# 'Guns n Roses',
# 'Booker T. and the MG',
# 'Nine Inch Nails',
# 'Lynyrd Skynyrd',
# 'Martha and the Vandellas',
# 'Diana Ross and the Supremes',
# 'Roxy Music',
# 'Curtis Mayfield',
# 'Lee Scratch Perry'
# 'Linkin Park',
# 'Avenged Sevenfold',
# 'Green Day',
# 'Snow Patrol',
# 'Korn',
# 'Nickelback',
# 'Slipknot',
# 'Fall Out Boy',
'System of a Down',
'Blink-182',
'Creed',
'Radiohead',
'Killswitch Engage',
'Coldplay',
'Disturbed',
'The Click Five',
'Porcupine Tree',
'Foo Fighters',
'Underoath',
'Audioslave',
'Papa Roach',
'Sum 41',
'Bullet For My Valentine',
'Tool',
'The Strokes',
'Weezer',
'Limp Bizkit',
'My Chemical Romance',
'Trivium',
'Animal Collective',
'Lifehouse',
'Deftones',
'Godsmack',
'Bon Jovi',
'Alter Bridge',
'Nine Inch Nails',
'Good Charlotte',
'Modest Mouse',
'Franz Ferdinand',
'Meshuggah',
'Drowning Pool',
'Switchfoot',
'Death Cab For Cutie',
'Jimmy Eat World',
'The Offspring',
'Interpol',
'Kings of Leon',
'The Bravery',
'Puddle of Mudd',
'Stained',
'The Black Keys',
'Muse',
'Breaking Benjamin',
'30 Seconds To Mars',
'U2',
'Hoobastank',
'New Found Glory',
'Evanescence',
'Yeah Yeah Yeahs',
'Seether',
'The Killers',
'Wiclo',
'Paramore',
'Our Lady Peace',
'Maroon 5',
'Queens of the Stone Age',
'LCD Soundsystem',
'Pearl Jam',
'Simple Plan',
'The Hives',
'Metallica',
'Arctic Monkeys',
'Red Hot Chili Peppers',
'The All-American Rejects',
'Shinedown',
'Rilo Kiley',
'Coheed and Cambria',
'The Vines',
'Skillet',
'Aerosmith',
'The Mars Volta',
'Shadows Fall',
'Daughtry',
'The Fray',
'The Black Dahlia Murder',
'Kaiser Chiefs',
'Incubus',
'AC/DC',
'Arcade Fire',
'Lamb of God',
'Opeth',
'Spoon',
'Nightwish',
'Dream Theater',
'Mastadon',
'Barenaked Ladies',
'Symphony X',
'Three Days Grace',
'The Von Bondies',
'Hatebreed',
'Olivia Rodrigo',
'Taylor Swift',
'Eminem',
'Juice WRLD',
'Drake',
'Ed Sheeran',
'J. Cole',
'Ariana Grande',
'Kanye West',
'Justin Bieber',
'Lana Del Rey',
'Billie Eilish',
'Julia Michaels',
'The Weeknd',
'Kendrick Lamar',
'BTS',
'Cardi B',
'Travis Scott',
'Lady Gaga',
'Mariah Carey',
'John Legend',
'Justin Timerlake',
'Usher',
'Beyoncé',
'Pharrell Williams',
'Alicia Keys',
'Kelly Clarkson',
'Katy Perry',
'Adele',
'Akon',
'Bruno Mars',
'Selena Gomez',
'Khalid',
'Imagine Dragons',
'One Direction',
'James TW',
'Lewis Capaldi',
'Lauv',
'Maisie Peters',
'Alec Benjamin',
'Lorde',
'James Arthur',
'Dean Lewis',
'Jacob Lee',
'Calum Scott',
'Troye Sivan',
'Passenger',
'John Mayer',
'James Bay',
'Sam Smith',
'Shawn Mendes'
]


def get_lyrics(arr, k):  # Write lyrics of k songs by each artist in arr
    c = 0  # Counter
    for name in arr:
        try:
            # To fetch by popularity too and then merge the lists
            # songsByTitle = (genius.search_artist(name, max_songs=k, sort='title')).songs
            # songsAll = list(songs)
            # for i in songsByTitle:
            #     if not any(x.id == i.id for x in songs):
            #         songsAll.append(i)
            # s = [song.lyrics for song in songsAll]
            songs = (genius.search_artist(name, max_songs=k, sort='popularity')).songs
            s = [song.lyrics for song in songs]
            file.write(f"\n \n   <| Song By {name} |>   \n \n".join(s))  # Deliminator
            c += 1
            print(f"Songs grabbed:{len(s)}")
        except Exception as inst:  #  Broad catch which will give us the name of artist and song that threw the exception
            print(type(inst))
            print(inst.args)
            print(inst)
            print(f"some exception at {name}: {c}")


get_lyrics(artists, 75)