import lyricsgenius as lg # https://github.com/johnwmillr/LyricsGenius


file = open("/mnt/f/lyrics_collection/artists2_all_songs_1.txt", "w")  # File to write lyrics to
genius = lg.Genius('aTh-Dc2WaOTlLdHP5p7xV_YpLke-MQvY9Ux_nfg68IcGikRld8yJZfIwSv6794L1',  # Client access token from Genius Client API page
                             skip_non_songs=True, excluded_terms=["(Remix)", "(Live)"],
                             remove_section_headers=True, timeout=30)

artists = [
'Logic',
'Rihanna',
'Frank Sinatra',
'The Beatles',
'Bob Dylan',
'Elvis Presley',
'Rolling Stones',
'Chuck Berry',
'Jimi Hendrix',
'James Brown',
'Little Richard',
'Aretha Franklin',
'Ray Charles',
'Bob Marley',
'The Beach Boys',
'Buddy Holly',
'Led Zeppelin',
'Stevie Wonder',
'Sam Cooke',
'Muddy Waters',
'Marvin Gaye',
'The Velvet Underground',
'Bo Diddley',
'Otis Redding',
'U2',
'Bruce Springsteen',
'Jerry Lee Lewis',
'Fats Domino',
'The Ramones',
'Nirvana',
'Prince',
'The Who',
'The Clash',
'Johnny Cash',
'Smokey Robinson & The Miracles',
'The Everly Brothers',
'Neil Young',
'Michael Jackson',
'Madonna',
'Roy Orbison',
'John Lennon',
'David Bowie',
'Simon and Garfunkel',
'The Doors',
'Van Morrison',
'Sly and the Family Stone',
'Public Enemy',
'The Byrds',
'Janis Joplin',
'Patti Smith',
'Run-DMC',
'Elton John',
'The Band',
'Howlin Wolf',
'Allman Brothers Band',
'Eric Clapton',
'Dr. Dre',
'Grateful Dead',
'Parliament Funkadelic',
'Aerosmith',
'Sex Pistols',
'Louis Jordan',
'Joni Mitchell',
'Tina Turner',
'Etta James',
'Phil Spector',
'The Kinks',
'Al Green',
'Cream',
'The Temptations',
'Jackie Wilson',
'Carl Perkins',
'The Police',
'Frank Zappa',
'AC/DC',
'Radiohead',
'Hank Williams',
'The Eagles',
'The Shirelles',
'Beastie Boys',
'The Stooges',
'The Four Tops',
'Elvis Costello',
'The Drifters',
'Eminem',
'N.W.A.',
'James Taylor',
'Black Sabbath',
'Tupac Shakur',
'Gram Parsons',
'Miles Davis',
'The Yardbirds',
'Carlos Santana',
'Ricky Nelson',
'Guns n Roses',
'Booker T. and the MG',
'Nine Inch Nails',
'Lynyrd Skynyrd',
'Martha and the Vandellas',
'Diana Ross and the Supremes',
'Roxy Music',
'Curtis Mayfield',
'Lee Scratch Perry'
'Linkin Park',
'Avenged Sevenfold',
'Green Day',
'Snow Patrol',
'Korn',
'Nickelback',
'Slipknot',
'Fall Out Boy',
'System of a Down',
'Blink-182',
'Creed',
'Radiohead',
'Killswitch Engage',
'Coldplay',
'Disturbed',
'The Click Five',
'Porcupine Tree',
'Foo Fighters',
'Underoath',
'Audioslave',
'Papa Roach',
'Sum 41',
'Bullet For My Valentine',
'Tool',
'The Strokes',
'Weezer',
'Limp Bizkit',
'My Chemical Romance',
'Trivium',
'Animal Collective',
'Lifehouse',
'Deftones',
'Godsmack',
'Bon Jovi',
'Alter Bridge',
'Nine Inch Nails',
'Good Charlotte',
'Modest Mouse',
'Franz Ferdinand',
'Meshuggah',
'Drowning Pool',
'Switchfoot',
'Death Cab For Cutie',
'Jimmy Eat World',
'The Offspring',
'Interpol',
'Kings of Leon',
'The Bravery',
'Puddle of Mudd',
'Stained',
'The Black Keys',
'Muse',
'Breaking Benjamin',
'30 Seconds To Mars',
'U2',
'Hoobastank',
'New Found Glory',
'Evanescence',
'Yeah Yeah Yeahs',
'Seether',
'The Killers',
'Wiclo',
'Paramore',
'Our Lady Peace',
'Maroon 5',
'Queens of the Stone Age',
'LCD Soundsystem',
'Pearl Jam',
'Simple Plan',
'The Hives',
'Metallica',
'Arctic Monkeys',
'Red Hot Chili Peppers',
'The All-American Rejects',
'Shinedown',
'Rilo Kiley',
'Coheed and Cambria',
'The Vines',
'Skillet',
'Aerosmith',
'The Mars Volta',
'Shadows Fall',
'Daughtry',
'The Fray',
'The Black Dahlia Murder',
'Kaiser Chiefs',
'Incubus',
'AC/DC',
'Arcade Fire',
'Lamb of God',
'Opeth',
'Spoon',
'Nightwish',
'Dream Theater',
'Mastadon',
'Barenaked Ladies',
'Symphony X',
'Three Days Grace',
'The Von Bondies',
'Hatebreed',
'Olivia Rodrigo',
'Taylor Swift',
'Eminem',
'Juice WRLD',
'Drake',
'Ed Sheeran',
'J. Cole',
'Ariana Grande',
'Kanye West',
'Justin Bieber',
'Lana Del Rey',
'Billie Eilish',
'Julia Michaels',
'The Weeknd',
'Kendrick Lamar',
'BTS',
'Cardi B',
'Travis Scott',
'Lady Gaga',
'Mariah Carey',
'John Legend',
'Justin Timerlake',
'Usher',
'Beyoncé',
'Pharrell Williams',
'Alicia Keys',
'Kelly Clarkson',
'Katy Perry',
'Adele',
'Akon',
'Bruno Mars',
'Selena Gomez',
'Khalid',
'Imagine Dragons',
'One Direction',
'James TW',
'Lewis Capaldi',
'Lauv',
'Maisie Peters',
'Alec Benjamin',
'Lorde',
'James Arthur',
'Dean Lewis',
'Jacob Lee',
'Calum Scott',
'Troye Sivan',
'Passenger',
'John Mayer',
'James Bay',
'Sam Smith',
'Shawn Mendes'
]

artists2 = ['youngboy never broke again','lil nas x','doja cat','lil baby','morgan wallen','rod wave','bad bunny','future','post malone','pop smoke','polo g','luke combs','lil uzi vert','lil durk','trippie redd','$uicideboy$','lil wayne','moneybagg yo','xxxtentacion','mac miller','the kid laroi','dababy','gunna','kevin gates','jack harlow','chris stapleton','tyler, the creator','jason aldean','chris brown','playboi carti','kodak black','megan thee stallion','dua lipa','a boogie wit da hoodie','g-eazy','young thug','meek mill','machine gun kelly','j. balvin','nf','baby keem','migos','luke bryan','nicki minaj','glass animals','lil tecca','halsey','thomas rhett','harry styles','fleetwood mac','kane brown','kid cudi','florida georgia line','queen','roddy ricch','dj khaled','21 savage','jhené aiko','lil peep','frank ocean','sleepy hallow','ynw melly','lil tjay','giveon','twenty one pilots','h.e.r','kacey musgraves','king von','blackbear','dan + shay','rauw alejandro','eslabon armado','eric church','george strait','2pac','tyler childers','pooh shiesty','kenny chesney','eagles','miley cyrus','blake shelton','russ','jay-z','sza','panic! at the disco','grupo firme','gucci mane','walker hayes','sam hunt','lee brice','42 dugg','the neighbourhood','tory lanez','the rolling stones','brent faiyaz','zac brown band','metro boomin','p!nk','nle choppa','summer walker','farruko','ozuna','kehlani','the lumineers','g herbo','a$ap rocky','karol g','wiz khalifa','miranda lambert','carrie underwood','maluma','joyner lucas','tom petty','onerepublic','notorious b.i.g.','big sean','est gee','joji','marshmello','bryson tiller','pitbull','jelly roll','tim mcgraw','old dominion','pink floyd','cody johnson','wizkid','childish gambino','five finger death punch','ajr','alan jackson','jonas brothers','upchurch','young dolph','original broadway cast of hamilton','calvin harris','jordan davis','billy joel','don toliver','50 cent','jon pardi','nelly','mo3',"guns n' roses",'anuel aa','big30','ski mask the slump god','marca mp','bo burnham','willow','creedence clearwater revival','gorillaz','lizzo','melanie martinez','maren morris','brooks & dunn','daddy yankee','aventura','tame impala','6lack','key glock','jason derulo','the chainsmokers','britney spears','nocap','camila cabello','demi lovato','trey songz','partynextdoor','iann dior','myke towers','dierks bentley','journey','cage the elephant','chris young','miguel','brantley gilbert','t.i.','elevation worship','justin timberlake','outkast','jack johnson','tee grizzley','hozier','keith urban','romeo santos','junior h','5 seconds of summer','tyga','jhay cortez','yung bleu','alessia cara','mitski','young jeezy','dustin lynch','kali uchis','nipsey hussle','sheff g','nav','cocomelon','måneskin','westside gunn','clairo','brett young','sublime','earth wind & fire','money man','jeremih','24kgoldn','christian nodal','greta van fleet','chief keef','2 chainz','ty dolla $ign','nas','toby keith','van halen','conan gray','tate mcrae','david guetta','el fantasma','shakira','t-pain','lil yachty','natanael cano','the black eyed peas','flo rida','calibre 50','parker mccollum','cole swindell','lauren daigle','saweetie','ne-yo','cody jinks','kelsea ballerini','banda sinaloense ms de sergio lizárraga','oliver tree','toosii','koe wetzel','bob marley, the wailers','gabby barrett','lil skies','michael bublé','steve lacy','garth brooks','rascal flatts','young nudy','bazzi','toby fox','riley green','tai verdes','jake owen','$not','mac demarco','wale','daryl hall, john oates','bring me the horizon','hardy','bebe rexha','rick ross','bee gees','zach bryan','schoolboy q','yo gotti','snoop dogg','bia','avicii','girl in red','cavetown','ella mai','ke$ha','luis r. conriquez','isaiah rashad','sech','los dos carnales','surfaces','rex orange county','yg','bob seger','sia','daniel caesar','pinkpantheress','whitney houston','lady a','mary j. blige','masked wolf','carin leon','lord huron','abba','los tucanes de tijuana','little big town','kid rock','mozzy','enya','darius rucker','brad paisley','alice in chains','justin moore','aaliyah','hillsong worship','mitchell tenpenny','carly pearce','enrique iglesias','shoreline mafia','billy currington','hank williams jr.','saint jhn','train','jazmine sullivan','mötley crüe','maverick city music','don omar','def leppard','chance the rapper','vance joy',"destiny's child",'chase atlantic','all time low','phil collins','diplo','ice cube','phoebe bridgers','tink','meghan trainor','yfn lucci','lil mosey','k camp','normani','3 doors down','colter wall','dj snake','los bukis','tech n9ne','lany','dmx','ava max','rae sremmurd','daft punk','los tigres del norte','city girls','chlöe','chase rice','nicky jam','jaydayoungan','selena','charlie puth','whiskey myers','a$ap ferg','foster the people','tones and i','hillsong united','silk sonic','ckay','sleepy john','mother mother','r. kelly','scotty mccreery','lainey wilson','smashing pumpkins','queen naija','vicente fernández','fetty wap','ellie goulding','kygo','lil darkie','comethazine','mumford & sons','vedo','ozzy osbourne','blackpink','ciara','yeat','a day to remember','fredo bang','avril lavigne','tom macdonald','casting crowns','niko moon','falling in reverse','los temerarios','ashnikko',"pi'erre bourne",'leon bridges','larry june','boney m.','steely dan','ryan hurd','sturgill simpson','bryce vine','willie nelson','jacquees','french montana','stray kids','blxst','jennifer lopez','needtobreathe','the chicks','alina baraz','quinn xcii']

def get_lyrics(arr, k):  # Write lyrics of k songs by each artist in arr
    c = 0  # Counter
    for name in arr:
        try:
            # To fetch by popularity too and then merge the lists
            # songsByTitle = (genius.search_artist(name, max_songs=k, sort='title')).songs
            # songsAll = list(songs)
            # for i in songsByTitle:
            #     if not any(x.id == i.id for x in songs):
            #         songsAll.append(i)
            # s = [song.lyrics for song in songsAll]
            songs = (genius.search_artist(name, max_songs=k, sort='popularity')).songs
            s = [song.lyrics for song in songs]
            file.write(f"\n \n   <| Song By {name} |>   \n \n".join(s))  # Deliminator
            c += 1
            print(f"Songs grabbed:{len(s)}")
        except Exception as inst:  #  Broad catch which will give us the name of artist and song that threw the exception
            print(type(inst))
            print(inst.args)
            print(inst)
            print(f"some exception at {name}: {c}")


# get_lyrics(artists, 75)
get_lyrics(artists2, 100)